services:
  - type: web
    name: retail-pos-backend
    env: node
    plan: free
    buildCommand: npm run build:backend
    startCommand: npm run start:backend
    envVars:
      - key: NODE_ENV
        value: production 