// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmclxgkwqupavtphuzwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptY2x4Z2t3cXVwYXZ0cGh1endhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODE3MTQsImV4cCI6MjA1OTg1NzcxNH0.yMSm9BidaID13V7IVOW-cKBSEM9A4FcdCRwP3dkRyjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);